version: "3.4"

services:
  kafka-ui:
    container_name: data-bus-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_started
      zookeeper:
        condition: service_started
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: data-bus-zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.3.1
    container_name: data-bus-kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: unless-stopped
    depends_on:
      - zookeeper

  data-bus-receiver:
    build: ../data-bus-receiver
    container_name: data-bus-receiver
    ports:
      - '9090:9090'
    restart: unless-stopped
    depends_on:
      - kafka

  data-bus-publisher:
    build: ../data-bus-publisher
    container_name: data-bus-publisher
    ports:
      - '9080:9080'
    restart: unless-stopped
    depends_on:
      - kafka
